"""Repository ports (typing.Protocol) — see docs/architecture.md.

Item is managed as part of the Bibliography aggregate: it never exists
without a parent bibliography, so item CRUD lives on BibliographyRepository
rather than a separate ItemRepository. The bibliography<->author link is
managed the same way (set_authors/list_authors on BibliographyRepository),
since a bibliography "owns" its author list; Author records themselves are
standalone master data, so their own CRUD lives on AuthorRepository instead
(mirroring MemberRepository).
"""

from typing import Protocol

from bibliosphere.domain.entities import Author, Bibliography, Item, Loan, Member


class BibliographyRepository(Protocol):
    def add(self, bibliography: Bibliography) -> Bibliography: ...
    def update(self, bibliography: Bibliography) -> None: ...
    def get_by_id(self, bibliography_id: int) -> Bibliography | None: ...
    def get_by_isbn(self, isbn: str) -> Bibliography | None: ...
    def search(self, query: str) -> list[Bibliography]: ...
    def list_all(self) -> list[Bibliography]: ...

    def add_item(self, bibliography_id: int) -> Item: ...
    def remove_item(self, item_id: int) -> None: ...
    def get_item(self, item_id: int) -> Item | None: ...
    def list_items(self, bibliography_id: int) -> list[Item]: ...

    def set_authors(self, bibliography_id: int, author_ids: list[int]) -> None: ...
    def list_authors(self, bibliography_id: int) -> list[Author]: ...


class AuthorRepository(Protocol):
    def add(self, author: Author) -> Author: ...
    def get_by_id(self, author_id: int) -> Author | None: ...
    def get_by_name(self, name: str) -> Author | None: ...
    def list_all(self) -> list[Author]: ...
    def find_or_create_by_name(self, name: str) -> Author: ...


class MemberRepository(Protocol):
    def add(self, member: Member) -> Member: ...
    def update(self, member: Member) -> None: ...
    def get_by_id(self, member_id: int) -> Member | None: ...
    def get_by_username(self, username: str) -> Member | None: ...
    def list_all(self) -> list[Member]: ...


class LoanRepository(Protocol):
    def add(self, loan: Loan) -> Loan: ...
    def update(self, loan: Loan) -> None: ...
    def get_by_id(self, loan_id: int) -> Loan | None: ...
    def get_open_loan_for_item(self, item_id: int) -> Loan | None: ...
    def list_open_loans_for_member(self, member_id: int) -> list[Loan]: ...
    def list_all_open_loans(self) -> list[Loan]: ...
    def count_open_loans_for_member(self, member_id: int) -> int: ...
