"""Repository ports (typing.Protocol) — see docs/architecture.md.

Item is managed as part of the Bibliography aggregate: it never exists
without a parent bibliography, so item CRUD lives on BibliographyRepository
rather than a separate ItemRepository. The bibliography<->author link is
managed the same way (set_authors/list_authors on BibliographyRepository),
since a bibliography "owns" its author list; Author records themselves are
standalone master data, so their own CRUD lives on AuthorRepository instead
(mirroring MemberRepository).
"""

from typing import Protocol

from bibliosphere.domain.entities import Author, Bibliography, BibliographyAuthor, Item, Loan, Member


class BibliographyRepository(Protocol):
    def add(self, bibliography: Bibliography) -> Bibliography: ...
    def update(self, bibliography: Bibliography) -> None: ...
    def remove(self, bibliography_id: int) -> None: ...
    def get_by_id(self, bibliography_id: int) -> Bibliography | None: ...
    def get_by_isbn(self, isbn: str) -> Bibliography | None: ...
    def get_by_call_number(self, call_number: str) -> Bibliography | None: ...
    def search(self, query: str) -> list[Bibliography]: ...
    def list_all(self) -> list[Bibliography]: ...

    def add_item(self, bibliography_id: int) -> Item: ...
    def remove_item(self, item_id: int) -> None: ...
    def get_item(self, item_id: int) -> Item | None: ...
    def list_items(self, bibliography_id: int) -> list[Item]: ...

    # author_ids order is preserved as the stored author level (1-based).
    def set_authors(self, bibliography_id: int, author_ids: list[int]) -> None: ...
    # Returns credits ordered by level.
    def list_authors(self, bibliography_id: int) -> list[BibliographyAuthor]: ...


class AuthorRepository(Protocol):
    def add(self, author: Author) -> Author: ...
    def get_by_id(self, author_id: int) -> Author | None: ...
    def get_by_name(self, name: str) -> Author | None: ...
    def list_all(self) -> list[Author]: ...
    def find_or_create_by_name(self, name: str) -> Author: ...


class MemberRepository(Protocol):
    def add(self, member: Member) -> Member: ...
    def update(self, member: Member) -> None: ...
    def get_by_id(self, member_id: str) -> Member | None: ...
    def get_by_username(self, username: str) -> Member | None: ...
    def list_all(self) -> list[Member]: ...


class LoanRepository(Protocol):
    def add(self, loan: Loan) -> Loan: ...
    def update(self, loan: Loan) -> None: ...
    def get_by_id(self, loan_id: int) -> Loan | None: ...
    def get_open_loan_for_item(self, item_id: int) -> Loan | None: ...
    def list_open_loans_for_member(self, member_id: str) -> list[Loan]: ...
    def list_all_open_loans(self) -> list[Loan]: ...
    # Every loan, open or returned — for the librarian-facing loan history view.
    def list_all(self) -> list[Loan]: ...
    def count_open_loans_for_member(self, member_id: str) -> int: ...


class UnitOfWork(Protocol):
    """Groups a use case's repository writes into one atomic transaction.

    For use cases with more than one write (e.g. AddBibliography creating a
    bibliography and then linking authors), wrapping the sequence in `with
    unit_of_work:` commits once at the end, or rolls back everything if any
    step raises — instead of each repository call committing independently,
    which can leave committed-but-incomplete state on a mid-sequence failure.
    """

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: object) -> None: ...
