"""Repository ports (typing.Protocol) — see docs/architecture.md.

Item is managed as part of the Bibliography aggregate: it never exists
without a parent bibliography, so item CRUD lives on BibliographyRepository
rather than a separate ItemRepository. The bibliography<->author link is
managed the same way (set_authors/list_authors on BibliographyRepository),
since a bibliography "owns" its author list; Author records themselves are
standalone master data, so their own CRUD lives on AuthorRepository instead
(mirroring MemberRepository).
"""

from dataclasses import dataclass
from datetime import date
from typing import Protocol

from bibliosphere.domain.entities import Author, Bibliography, BibliographyAuthor, Item, Loan, Member


class BibliographyRepository(Protocol):
    def add(self, bibliography: Bibliography) -> Bibliography: ...
    def update(self, bibliography: Bibliography) -> None: ...
    def remove(self, bibliography_id: int) -> None: ...
    def get_by_id(self, bibliography_id: int) -> Bibliography | None: ...
    def get_by_isbn(self, isbn: str) -> Bibliography | None: ...
    def get_by_call_number(self, call_number: str) -> Bibliography | None: ...
    def search(self, query: str) -> list[Bibliography]: ...
    def list_all(self) -> list[Bibliography]: ...

    def add_item(self, bibliography_id: int) -> Item: ...
    def remove_item(self, item_id: int) -> None: ...
    def get_item(self, item_id: int) -> Item | None: ...
    def list_items(self, bibliography_id: int) -> list[Item]: ...

    # author_ids order is preserved as the stored author level (1-based).
    def set_authors(self, bibliography_id: int, author_ids: list[int]) -> None: ...
    # Returns credits ordered by level.
    def list_authors(self, bibliography_id: int) -> list[BibliographyAuthor]: ...


class AuthorRepository(Protocol):
    def add(self, author: Author) -> Author: ...
    def get_by_id(self, author_id: int) -> Author | None: ...
    def get_by_name(self, name: str) -> Author | None: ...
    def list_all(self) -> list[Author]: ...
    def find_or_create_by_name(self, name: str) -> Author: ...


class MemberRepository(Protocol):
    def add(self, member: Member) -> Member: ...
    def update(self, member: Member) -> None: ...
    def get_by_id(self, member_id: str) -> Member | None: ...
    def get_by_username(self, username: str) -> Member | None: ...
    def list_all(self) -> list[Member]: ...


@dataclass
class LoanHistoryFilters:
    """Per-column substring filters for LoanRepository.count_history/list_history_page.

    An empty string means "no filter on this column" — mirrors LoanHistoryView's
    per-column filter boxes. `status` matches against the literal words "checked out"
    / "returned" (e.g. "out" matches only checked-out loans).

    `checkout_date_from`/`checkout_date_to` are a separate range filter (inclusive on
    both ends), distinct from the `checkout_date` substring filter above — the range
    is what LoanHistoryView's dedicated date-range picker sets; `checkout_date` is
    still available for substring matches (e.g. "2026-03") within that range.
    """

    member_id: str = ""
    member_name: str = ""
    title: str = ""
    checkout_date: str = ""
    due_date: str = ""
    return_date: str = ""
    status: str = ""
    checkout_date_from: date | None = None
    checkout_date_to: date | None = None


class LoanRepository(Protocol):
    def add(self, loan: Loan) -> Loan: ...
    def update(self, loan: Loan) -> None: ...
    def get_by_id(self, loan_id: int) -> Loan | None: ...
    def get_open_loan_for_item(self, item_id: int) -> Loan | None: ...
    # True if the item has ever been loaned, open or returned — an item's loan rows
    # outlive the item itself (see ItemHasLoanHistory), so this must be checked
    # before removing an item, not just whether it's currently checked out.
    def has_any_loan_for_item(self, item_id: int) -> bool: ...
    def list_open_loans_for_member(self, member_id: str) -> list[Loan]: ...
    def list_all_open_loans(self) -> list[Loan]: ...
    def count_open_loans_for_member(self, member_id: str) -> int: ...

    # Loan history is unbounded over the library's lifetime (see docs/requirements.md
    # §6.1), so it's paginated and filtered at the repository rather than loaded whole.
    def count_history(self, filters: LoanHistoryFilters) -> int: ...
    def list_history_page(self, filters: LoanHistoryFilters, *, page: int, page_size: int) -> list[Loan]: ...


class UnitOfWork(Protocol):
    """Groups a use case's repository writes into one atomic transaction.

    For use cases with more than one write (e.g. AddBibliography creating a
    bibliography and then linking authors), wrapping the sequence in `with
    unit_of_work:` commits once at the end, or rolls back everything if any
    step raises — instead of each repository call committing independently,
    which can leave committed-but-incomplete state on a mid-sequence failure.
    """

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: object) -> None: ...
